-- 성장·보상 DB 1단계
-- 기존 campus_* 테이블과 분리된 개인 성장 원장입니다.
-- 팀 Supabase로 이관할 때도 이 파일을 그대로 실행할 수 있도록 작성합니다.

create table if not exists public.progression_balances (
  user_id uuid primary key references auth.users(id) on delete cascade,
  xp bigint not null default 0 check (xp >= 0),
  points bigint not null default 0 check (points >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.progression_reward_rules (
  event_type text primary key,
  xp_delta integer not null default 0 check (xp_delta >= 0),
  points_delta integer not null default 0 check (points_delta >= 0),
  enabled boolean not null default true,
  updated_at timestamptz not null default now()
);

insert into public.progression_reward_rules (event_type, xp_delta, points_delta)
values
  ('recovery_success', 25, 5),
  ('session_completed', 60, 30),
  ('stretch_completed', 10, 10),
  ('goal_completed', 15, 10),
  ('friend_session_bonus', 20, 10),
  ('streak_bonus', 0, 0)
on conflict (event_type) do nothing;

create table if not exists public.progression_reward_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_id text not null,
  event_type text not null references public.progression_reward_rules(event_type),
  source_session_id text,
  xp_delta integer not null check (xp_delta >= 0),
  points_delta integer not null check (points_delta >= 0),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (user_id, event_id)
);

create index if not exists progression_reward_events_user_created_idx
  on public.progression_reward_events (user_id, created_at desc);

alter table public.progression_balances enable row level security;
alter table public.progression_reward_rules enable row level security;
alter table public.progression_reward_events enable row level security;

drop policy if exists progression_balances_select_own on public.progression_balances;
create policy progression_balances_select_own
  on public.progression_balances for select to authenticated
  using (user_id = auth.uid());

drop policy if exists progression_reward_events_select_own on public.progression_reward_events;
create policy progression_reward_events_select_own
  on public.progression_reward_events for select to authenticated
  using (user_id = auth.uid());

revoke all on public.progression_reward_rules from anon, authenticated;
revoke insert, update, delete on public.progression_balances from anon, authenticated;
revoke insert, update, delete on public.progression_reward_events from anon, authenticated;
grant select on public.progression_balances, public.progression_reward_events to authenticated;

create or replace function public.apply_progression_reward(
  p_event_id text,
  p_event_type text,
  p_source_session_id text default null,
  p_metadata jsonb default '{}'::jsonb
) returns table (
  applied boolean,
  xp_delta integer,
  points_delta integer,
  total_xp bigint,
  total_points bigint,
  reason text
)
language plpgsql
security definer
set search_path = public
as $fn$
declare
  v_user_id uuid := auth.uid();
  v_rule public.progression_reward_rules%rowtype;
  v_event public.progression_reward_events%rowtype;
  v_balance public.progression_balances%rowtype;
begin
  if v_user_id is null then
    return query select false, 0, 0, 0::bigint, 0::bigint, 'authentication_required'::text;
    return;
  end if;

  if nullif(trim(p_event_id), '') is null then
    return query select false, 0, 0, 0::bigint, 0::bigint, 'event_id_required'::text;
    return;
  end if;

  select * into v_rule
    from public.progression_reward_rules
   where event_type = p_event_type and enabled;
  if not found then
    return query select false, 0, 0, 0::bigint, 0::bigint, 'unknown_or_disabled_event'::text;
    return;
  end if;

  insert into public.progression_balances (user_id)
  values (v_user_id)
  on conflict (user_id) do nothing;

  select * into v_balance
    from public.progression_balances
   where user_id = v_user_id
   for update;

  select * into v_event
    from public.progression_reward_events
   where user_id = v_user_id and event_id = p_event_id;
  if found then
    return query select false, v_event.xp_delta, v_event.points_delta,
      v_balance.xp, v_balance.points, 'duplicate'::text;
    return;
  end if;

  insert into public.progression_reward_events
    (user_id, event_id, event_type, source_session_id, xp_delta, points_delta, metadata)
  values
    (v_user_id, p_event_id, p_event_type, p_source_session_id,
     v_rule.xp_delta, v_rule.points_delta, coalesce(p_metadata, '{}'::jsonb));

  update public.progression_balances
     set xp = xp + v_rule.xp_delta,
         points = points + v_rule.points_delta,
         updated_at = now()
   where user_id = v_user_id
   returning * into v_balance;

  return query select true, v_rule.xp_delta, v_rule.points_delta,
    v_balance.xp, v_balance.points, 'applied'::text;
end;
$fn$;

revoke all on function public.apply_progression_reward(text, text, text, jsonb)
  from public, anon, authenticated;
grant execute on function public.apply_progression_reward(text, text, text, jsonb)
  to authenticated;
